kafka:
  podLabels:
    branch: $BRANCH_NAME
    resource: pod
    team: platform
    usage: utests
  tolerations:
    - key: team
      operator: Equal
      value: platform
      effect: NoSchedule
  nodeSelector:
    team: platform
  extraEnvVars:
    - name: KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE
      value: "false"
    - name: KAFKA_CFG_GROUP_INITIAL_REBALANCE_DELAY_MS
      value: "100"
    - name: KAFKA_CFG_LOG_RETENTION_MINUTES
      value: "20"
    - name: KAFKA_CFG_OFFSETS_RETENTION_MINUTES
      value: "20"
    - name: KAFKA_CFG_OFFSETS_TOPIC_NUM_PARTITIONS
      value: "5"
    - name: KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR
      value: "1"
    - name: KAFKA_CFG_STATE_LOG_REPLICATION_FACTOR
      value: "1"
  zookeeper:
    podLabels:
      branch: $BRANCH_NAME
      resource: pod
      team: platform
      usage: utests
    tolerations:
      - key: team
        operator: Equal
        value: platform
        effect: NoSchedule
    nodeSelector:
      team: platform
tags:
  kafka: true
